name: go.mod check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: go.mod check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: 1.17

      - name: Check go.mod files
        shell: bash
        run: |
          cd gomod-sync
          go run main.go check
